# Generated by Django 4.1.2 on 2023-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=25)),
                ('correo_usuario', models.EmailField(max_length=50, unique=True)),
                ('password_usuario', models.CharField(max_length=25)),
                ('telefono_usuario', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
